// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for City documents */
interface CityDocumentData {
    /**
     * Name field in *City*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: city.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
}
/**
 * City document from Prismic
 *
 * - **API ID**: `city`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CityDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<CityDocumentData>, "city", Lang>;
/** Content for Experience documents */
interface ExperienceDocumentData {
    /**
     * Title field in *Experience*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: experience.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Experience*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: experience.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Region field in *Experience*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: experience.region
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    region: prismicT.RelationField<"region">;
    /**
     * City field in *Experience*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: experience.city
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    city: prismicT.RelationField<"city">;
    /**
     * locations field in *Experience*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: experience.locations[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    locations: prismicT.GroupField<Simplify<ExperienceDocumentDataLocationsItem>>;
    /**
     * Slice Zone field in *Experience*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: experience.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ExperienceDocumentDataSlicesSlice>;
}
/**
 * Item in Experience → locations
 *
 */
export interface ExperienceDocumentDataLocationsItem {
    /**
     * Region field in *Experience → locations*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: experience.locations[].region
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    region: prismicT.RelationField<"region">;
}
/**
 * Slice for *Experience → Slice Zone*
 *
 */
type ExperienceDocumentDataSlicesSlice = never;
/**
 * Experience document from Prismic
 *
 * - **API ID**: `experience`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExperienceDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ExperienceDocumentData>, "experience", Lang>;
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = ImageTextCtaSlice | TextBlockSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Region documents */
interface RegionDocumentData {
    /**
     * Name field in *Region*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: region.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
}
/**
 * Region document from Prismic
 *
 * - **API ID**: `region`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RegionDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<RegionDocumentData>, "region", Lang>;
/** Content for Thematique documents */
interface ThematiqueDocumentData {
    /**
     * Name field in *Thematique*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: thematique.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.RichTextField;
    /**
     * Title field in *Thematique*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: thematique.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Image field in *Thematique*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: thematique.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *Thematique*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: thematique.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ThematiqueDocumentDataSlicesSlice>;
}
/**
 * Slice for *Thematique → Slice Zone*
 *
 */
type ThematiqueDocumentDataSlicesSlice = never;
/**
 * Thematique document from Prismic
 *
 * - **API ID**: `thematique`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ThematiqueDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ThematiqueDocumentData>, "thematique", Lang>;
export type AllDocumentTypes = CityDocument | ExperienceDocument | HomepageDocument | RegionDocument | ThematiqueDocument;
/**
 * Primary content in CardImageText → Primary
 *
 */
interface CardImageTextSliceDefaultPrimary {
    /**
     * Title field in *CardImageText → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Card title
     * - **API ID Path**: card_image_text.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Image field in *CardImageText → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card_image_text.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * link_path field in *CardImageText → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: card_image_text.primary.link_path
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_path: prismicT.LinkField;
}
/**
 * Default variation for CardImageText Slice
 *
 * - **API ID**: `default`
 * - **Description**: `CardImageText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CardImageTextSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<CardImageTextSliceDefaultPrimary>, never>;
/**
 * Slice variation for *CardImageText*
 *
 */
type CardImageTextSliceVariation = CardImageTextSliceDefault;
/**
 * CardImageText Shared Slice
 *
 * - **API ID**: `card_image_text`
 * - **Description**: `CardImageText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CardImageTextSlice = prismicT.SharedSlice<"card_image_text", CardImageTextSliceVariation>;
/**
 * Primary content in ImageTextCta → Primary
 *
 */
interface ImageTextCtaSliceDefaultPrimary {
    /**
     * Image field in *ImageTextCta → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_text_cta.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Title field in *ImageTextCta → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: image_text_cta.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *ImageTextCta → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: image_text_cta.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Cta link field in *ImageTextCta → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: My link
     * - **API ID Path**: image_text_cta.primary.cta_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    cta_link: prismicT.LinkField;
    /**
     * Cta_text field in *ImageTextCta → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: My link's text here
     * - **API ID Path**: image_text_cta.primary.cta_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_text: prismicT.KeyTextField;
}
/**
 * Default variation for ImageTextCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ImageTextCta`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageTextCtaSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImageTextCtaSliceDefaultPrimary>, never>;
/**
 * Primary content in ImageTextCta → Primary
 *
 */
interface ImageTextCtaSliceImageRightSidePrimary {
    /**
     * Image field in *ImageTextCta → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_text_cta.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Title field in *ImageTextCta → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: image_text_cta.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *ImageTextCta → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: image_text_cta.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Cta link field in *ImageTextCta → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: My link
     * - **API ID Path**: image_text_cta.primary.cta_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    cta_link: prismicT.LinkField;
    /**
     * Cta_text field in *ImageTextCta → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: My link's text here
     * - **API ID Path**: image_text_cta.primary.cta_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_text: prismicT.KeyTextField;
}
/**
 * ImageRightSide variation for ImageTextCta Slice
 *
 * - **API ID**: `imageRightSide`
 * - **Description**: `ImageTextCta`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageTextCtaSliceImageRightSide = prismicT.SharedSliceVariation<"imageRightSide", Simplify<ImageTextCtaSliceImageRightSidePrimary>, never>;
/**
 * Slice variation for *ImageTextCta*
 *
 */
type ImageTextCtaSliceVariation = ImageTextCtaSliceDefault | ImageTextCtaSliceImageRightSide;
/**
 * ImageTextCta Shared Slice
 *
 * - **API ID**: `image_text_cta`
 * - **Description**: `ImageTextCta`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageTextCtaSlice = prismicT.SharedSlice<"image_text_cta", ImageTextCtaSliceVariation>;
/**
 * Primary content in TextBlock → Primary
 *
 */
interface TextBlockSliceDefaultPrimary {
    /**
     * Title field in *TextBlock → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: text_block.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *TextBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: text_block.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TextBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TextBlockSliceDefaultPrimary>, never>;
/**
 * Primary content in TextBlock → Primary
 *
 */
interface TextBlockSliceTextBlockColumnsPrimary {
    /**
     * Title field in *TextBlock → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: text_block.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *TextBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: text_block.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * TextBlockColumns variation for TextBlock Slice
 *
 * - **API ID**: `textBlockColumns`
 * - **Description**: `TextBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSliceTextBlockColumns = prismicT.SharedSliceVariation<"textBlockColumns", Simplify<TextBlockSliceTextBlockColumnsPrimary>, never>;
/**
 * Slice variation for *TextBlock*
 *
 */
type TextBlockSliceVariation = TextBlockSliceDefault | TextBlockSliceTextBlockColumns;
/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: `TextBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSlice = prismicT.SharedSlice<"text_block", TextBlockSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { CityDocumentData, CityDocument, ExperienceDocumentData, ExperienceDocumentDataLocationsItem, ExperienceDocumentDataSlicesSlice, ExperienceDocument, HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, RegionDocumentData, RegionDocument, ThematiqueDocumentData, ThematiqueDocumentDataSlicesSlice, ThematiqueDocument, AllDocumentTypes, CardImageTextSliceDefaultPrimary, CardImageTextSliceDefault, CardImageTextSliceVariation, CardImageTextSlice, ImageTextCtaSliceDefaultPrimary, ImageTextCtaSliceDefault, ImageTextCtaSliceImageRightSidePrimary, ImageTextCtaSliceImageRightSide, ImageTextCtaSliceVariation, ImageTextCtaSlice, TextBlockSliceDefaultPrimary, TextBlockSliceDefault, TextBlockSliceTextBlockColumnsPrimary, TextBlockSliceTextBlockColumns, TextBlockSliceVariation, TextBlockSlice };
    }
}
