// Code generated by Slice Machine. DO NOT EDIT.

import CardImageText from './CardImageText';
import ImageTextCta from './ImageTextCta';
import TextBlock from './TextBlock';

export {
	CardImageText,
	ImageTextCta,
	TextBlock,
};

export const components = {
	card_image_text: CardImageText,
	image_text_cta: ImageTextCta,
	text_block: TextBlock,
};
