import Head from "next/head";
import { GetStaticPropsContext, NextPage } from "next";
import { SliceZone } from "@prismicio/react";
import type { Content } from "@prismicio/client";
import { components } from "../../slices";
import { createClient } from "../../prismicio";
import Link from "next/link";

interface IProps {
  page: Content.HomepageDocument;
  experiences: Content.ExperienceDocument[];
  thematics: Content.ThematiqueDocument[];
  regions: Content.RegionDocument[];
}

const Homepage: NextPage<IProps> = ({
  page,
  experiences,
  thematics,
  regions,
}) => {
  return (
    <>
      <Head>
        <title>Prismic TS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2 className="my-8 text-center text-xl">Prismic TS TailwindCss</h2>
        <div className="py-8 mx-2">
          <div className="py-2">
            <h2 className="uppercase">Expériences</h2>
            <div className="flex items-center gap-2 mt-2">
              {experiences.map((experience: Content.ExperienceDocument, i) => (
                <Link
                  href={{
                    pathname: "/experience/[uid]",
                    query: { uid: experience.uid },
                  }}
                  key={i}
                  className="bg-blue-800 hover:bg-blue-700 hover:shadow-lg transition text-white rounded-md py-2 px-4"
                >
                  {experience.data.title[0].text}
                </Link>
              ))}
            </div>
          </div>

          <div className="py-2">
            <h2 className="uppercase">Thématiques</h2>
            <div className="flex items-center gap-2 mt-2">
              {thematics.map((thematic: Content.ThematiqueDocument, i) => (
                <Link
                  href={{
                    pathname: "/thematique/[uid]",
                    query: { uid: thematic.uid },
                  }}
                  key={i}
                  className="bg-green-800 hover:bg-green-700 hover:shadow-lg transition text-white rounded-md py-2 px-4"
                >
                  {thematic.data.name[0].text}
                </Link>
              ))}
            </div>
          </div>

          <div className="py-2">
            <h2 className="uppercase">Régions</h2>
            <div className="flex items-center gap-2 mt-2">
              {regions.map((region: Content.RegionDocument, i) => (
                <Link
                  href={{
                    pathname: "/location/[uid]",
                    query: { uid: region.uid },
                  }}
                  key={i}
                  className="bg-yellow-800 hover:bg-yellow-700 hover:shadow-lg transition text-white rounded-md py-2 px-4"
                >
                  {region.data.name}
                </Link>
              ))}
            </div>
          </div>
        </div>

        <SliceZone slices={page.data.slices} components={components} />
      </main>
    </>
  );
};

export default Homepage;

export async function getStaticProps({ previewData }: GetStaticPropsContext) {
  const client = createClient({ previewData });

  const page = await client.getSingle("homepage");

  const experiences = await client.getAllByType("experience");
  const thematics = await client.getAllByType("thematique");
  const regions = await client.getAllByType("region");

  return { props: { page, experiences, thematics, regions } };
}
