import Head from "next/head";
import { GetStaticPropsContext, NextPage } from "next";
import { SliceZone } from "@prismicio/react";
import type { Content } from "@prismicio/client";
import { components } from "../../slices";
import { createClient } from "../../prismicio";
import Link from "next/link";

interface IProps {
  page: Content.HomepageDocument;
}

const Homepage: NextPage<IProps> = ({ page }) => {
  return (
    <>
      <Head>
        <title>Prismic TS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SliceZone slices={page.data.slices} components={components} />
      </main>

      <div className="my-8 text-center">
        <Link
          href={{
            pathname: "/thematique/[uid]",
            query: { uid: "randonnee" },
          }}
          className="bg-slate-800 hover:bg-slate-700 hover:shadow-lg transition text-white rounded-md py-4 px-8"
        >
          Vers thématique
        </Link>
      </div>
    </>
  );
};

export default Homepage;

export async function getStaticProps({ previewData }: GetStaticPropsContext) {
  const client = createClient({ previewData });

  const page = await client.getSingle("homepage");

  return { props: { page } };
}
