// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blank_space: dynamic(() => import("./BlankSpace")),
  image_text_cta: dynamic(() => import("./ImageTextCta")),
  text_block: dynamic(() => import("./TextBlock")),
};
